server.port=8086
spring.application.name=lease-service

# Configuración de Base de Datos (MySQL)
spring.datasource.url=jdbc:mysql://localhost:3306/db_leases?serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=

# Configuración de JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
