server.port=8085
spring.application.name=tenant-service

# Configuración de Base de Datos (MySQL)
spring.datasource.url=jdbc:mysql://localhost:3306/db_tenants
spring.datasource.username=root
spring.datasource.password=ServBay.dev

# Configuración de JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect


eureka.client.enabled=false