version: '3.8'

services:
  # 1. EL CONTENEDOR DE LA BASE DE DATOS
  mysql-auth:
    image: mysql:8.0
    container_name: db_auth_container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_auth # Docker crea el esquema vacío automáticamente
    ports:
      - "3307:3306" # Lo exponemos en el 3307 para que no choque con tu Laragon en Windows
    volumes:
      - auth_db_data:/var/lib/mysql # Guarda los datos para que no se borren si apagas Docker

  # 2. EL CONTENEDOR DE TU MICROSERVICIO
  auth-service:
    build: . # Le dice a Docker que construya la imagen usando el Dockerfile de esta carpeta
    container_name: auth_service_container
    ports:
      - "8081:8081"
    depends_on:
      - mysql-auth # Obliga a esperar que MySQL encienda primero
    restart: on-failure
    environment:
      # Sobrescribimos las variables de tu application.properties
      - spring.datasource.url=jdbc:mysql://mysql-auth:3306/db_auth?serverTimezone=UTC
      - spring.datasource.username=root
      - spring.datasource.password=root

volumes:
  auth_db_data: