# Identidad y Puerto
spring.application.name=api-gateway
server.port=8080

# Configuración de Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/


# Ruta para AUTH-SERVICE
spring.cloud.gateway.server.webflux.routes[0].id=auth-service
spring.cloud.gateway.server.webflux.routes[0].uri=lb://AUTH-SERVICE
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/auth/**

# Ruta para UTILITY-SERVICE
spring.cloud.gateway.server.webflux.routes[1].id=utility-service
spring.cloud.gateway.server.webflux.routes[1].uri=lb://UTILITY-SERVICE
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/utility/**