spring.application.name=inventory-service

server.port=8083

# Configuración de Base de Datos (Laragon)
spring.datasource.url=jdbc:mysql://localhost:3306/db_invetario?createDatabaseIfNotExist=true&serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuración JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect # Hibernate lo detectará automáticamente


# Registro en Eureka (Desactivado para pruebas locales si no hay servidor Eureka)
spring.cloud.discovery.enabled=false
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/